server:
    interface: 0.0.0.0
    port: 53
    access-control: 0.0.0.0/0 allow
    username: ""
    chroot: ""
    directory: "/etc/unbound"
    pidfile: "/tmp/unbound.pid"
    verbosity: 1
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    edns-buffer-size: 4096
    max-udp-size: 4096
    msg-buffer-size: 65552
    harden-glue: no
    harden-dnssec-stripped: no
    harden-referral-path: no
    use-caps-for-id: no
    qname-minimisation: no
    module-config: "python iterator"
    cache-min-ttl: 0
    cache-max-ttl: 30
    prefetch: no
    so-reuseport: no
    outgoing-num-tcp: 10
    incoming-num-tcp: 10

stub-zone:
    name: "bank.com."
    stub-addr: 10.82.0.100
    stub-prime: no

remote-control:
    control-enable: yes
    control-interface: "/tmp/unbound-control.sock"
    control-use-cert: no

python:
    python-script: "/etc/unbound/e5mod.py"
